Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "file", source: "empty", destination: "empty"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3
	apt-get install -y python3-pip
	apt-get install -y python3-psycopg2
	pip3 install Django
  SHELL
end
